spring.application.name=albaran

spring.datasource.url=jdbc:postgresql://localhost:3000/albaran_db
spring.datasource.username=postgres
spring.datasource.password=Ada86088608!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Driver
spring.datasource.driver-class-name=org.postgresql.Driver
