spring.datasource.url=${db_url}
spring.datasource.username=${db_user}
spring.datasource.password=${db_pass}

spring.jpa.hibernate.ddl-auto=validate
spring.application.name=albaran
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
server.tomcat.threads.min-spare=2
server.tomcat.threads.max=10
